### ISSUE TITLE
issue with v1.33 v1.40

### ISSUE THREAD

**Issue by KappesBuur** [edge-classic/EDGE-classic#464]
[img]https://i.imgur.com/BAte3oP.png[/img]

when I try to run ec from UDB

resolved: IWAD was set to read-only
but then the question arises why the IWAD does not work when it is ready-onle
none of the other ports care, they just work

**Comment by dashodanger** [comment]
I am not sure what you mean by "v1.40", as we have not made such a release. The version of AJBSP in the 1.33 codebase attempts to open a WAD in "append" mode, and if it cannot, produces the error message in your screenshot. This is because AJBSP by default is intended to add nodes to an existing WAD in-place. Like I mentioned in the last issue you opened for this, we have since fixed the issue and in future releases AJBSP will only open a WAD in "read" mode.
