### ISSUE TITLE
Multiple iWADs break the launcher under Linux

### ISSUE THREAD

**Issue by vanessakindell** [edge-classic/EDGE-classic#690]
Multiple iWADs break the game selection menu under Linux and return a "Error in game selection dialogue!"

These are:
- hacx.wad
- harm1.wad
- heretic.wad
- rekkr.wad
- strife.wad (& voices.wad)

Current workaround: use the -iwad switch to select them manually via command line.

![image](https://github.com/edge-classic/EDGE-classic/assets/16767721/612c2258-fee0-4620-ac17-99afa181214a)

**Comment by dashodanger** [comment]
This message actually appears when the SDL_ShowMessageBox function fails for the IWAD selector. I have added SDL_GetError to the print statement that produces this message in order to get a better idea of what is happening. Please recompile with commit https://github.com/edge-classic/EDGE-classic/commit/712bd3010c0ceba069f2fb320e0c4d74cf79c8c6 or later and show the output if you can recreate this situation.

**Comment by vanessakindell** [comment]
Updated error message from latest pull
![image](https://github.com/edge-classic/EDGE-classic/assets/16767721/843e27b1-5b02-4458-9f17-435bcca16766)

**Comment by dashodanger** [comment]
It looks like SDL has a hard coded limit of 8 buttons for some backends when using SDL_ShowMessageBox. I have pushed https://github.com/edge-classic/EDGE-classic/commit/a91e2950eaddf6746dbebfaf9e5d2ab080b2ca0f to limit the number of IWADs presented to the user to 8, with additional advice to use a launcher if more than this is needed for automatic IWAD detection
