### ISSUE TITLE
Wolfenstein EC slider doors sometimes do not block sound

### ISSUE THREAD

**Issue by LoboEire** [edge-classic/EDGE-classic#733]
Our stock slider doors do block sound correctly, but the ones in WolfEC do not for some reason.

**Comment by dashodanger** [comment]
Upon further investigation, looks like some of the sliding door lines in WolfEC have the same sector index for their front and back side; this means that RecurseSound can still successfully traverse the sector if there are non-blocking lines on each side of the door in this case. This has to be fixed in the maps vs. the engine.
